use serde::{Serialize, Deserialize};
use ed25519_dalek::{SigningKey, VerifyingKey, Signature, Signer, Verifier};
use x25519_dalek::PublicKey as X25519PublicKey;

#[derive(Serialize, Deserialize, Debug)]
pub struct HandshakeMessage {
    pub identity_key: [u8; 32],
    pub ephemeral_key: [u8; 32],
    pub signature: [u8; 64],
}

impl HandshakeMessage {
    // Construct a new handshake and cryptographically sign the throwaway ephemeral key
    pub fn new(identity_sk: &SigningKey, ephemeral_pk: &X25519PublicKey) -> Self {
        let identity_vk = VerifyingKey::from(identity_sk);
        let ephemeral_bytes = ephemeral_pk.as_bytes();
        
        let signature = identity_sk.sign(ephemeral_bytes).to_bytes();
        
        Self {
            identity_key: identity_vk.to_bytes(),
            ephemeral_key: *ephemeral_bytes,
            signature,
        }
    }

    pub fn serialize(&self) -> Vec<u8> {
        bincode::serialize(self).unwrap()
    }

    // Zero-trust verification: Ensure the ephemeral key was actually generated by the stated identity
    pub fn verify_signature(&self) -> bool {
        if let Ok(vk) = VerifyingKey::from_bytes(&self.identity_key) {
            let sig = Signature::from_bytes(&self.signature);
            vk.verify(&self.ephemeral_key, &sig).is_ok()
        } else {
            false
        }
    }
}
